server:
  port: 80

spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: 39.102.82.123
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        # 心跳协议
        heartbeat:
          enabled: true
